# Idea of separation based on this forum entry:
# https://discourse.gohugo.io/t/two-themes-as-separate-hugo-directories-deployed-to-the-same-website/27899/4
# vim: set ts=2 sts=2 sw=2 expandtab:
defaultContentLanguage = "en"
languageCode = "en"
title = "Maciej Bliziński"
baseurl = "https://blizin.ski/bio"
theme = "hugo-split-theme"
rssLimit = 20
enableGitInfo = true
contentDir = "content/bio"
publishDir = "public/bio"
staticDir = "static/bio"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
copyright = "&copy;2024 Maciej Bliziński"
[author]
  [author.maciej]
    name = "Maciej Bliziński"
    email = "maciej.blizinski@gmail.com"

[params]
  authorName = "Maciej Bliziński"
  authorEmail = "maciej.blizinski@gmail.com"
  siteLogo = "/images/automaciej-logo.jpg"
  twitterHandle = "automaciej"
  githubName = "automaciej"
  facebookUrlPath = "maciej.blizinski"
  tiktokName = "automaciej"
  instagramHandle = "mblizinski"
  mastodonLink = "https://mastodon.ie/@automaciej"
  description = "Bass player in Dublin, Ireland; jazz, bossa nova, samba, chorinho"
  shareImage = "images/maciej_on_bass_hi.jpg"
  [params.visual]
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
  [[params.links]]
    [params.links.list1]
      heading = "Connect"
      [[params.links.list1.link]]
        text = "linktr.ee"
        url = "http://linktr.ee/mblizinski"

    [params.links.list2]
      heading = "Social"
      [[params.links.list2.link]]
        text = "Instagram"
        url = "http://instagram.com/mblizinski"
      [[params.links.list2.link]]
        text = "Facebook"
        url = "http://facebook.com/maciej.blizinski"
      [[params.links.list2.link]]
        text = "TikTok"
        url = "http://tiktok.com/@automaciej"
      [[params.links.list2.link]]
        text = "SoundCloud"
        url = "http://soundcloud.com/maciej-blizinski"

    [params.links.list3]
      heading = "More"
      [[params.links.list3.link]]
        text = "About Maciej"
        url = "/bio/about"
      [[params.links.list3.link]]
        text = "Music"
        url = "/bio/music"
      [[params.links.list3.link]]
        text = "Press"
        url = "/bio/press"
      [[params.links.list3.link]]
        text = "Photos"
        url = "/bio/photos"
      [[params.links.list3.link]]
        text = "Performances"
        url = "/bio/performances"

[blackfriday]
  # W przypisach mamy rzeczy typu "2010/4" które są formami dat.
  fractions = false
[imaging.exif]
  includeFields = ".*"
