name = "Theme004"
license = "MIT"
# Not a real license.
licenselink = "https://github.com/automatthias/automaciej-hugo/blob/master/themes/theme004/LICENSE"
description = "A 2017 theme for my personal blog."
homepage = "http://blizin.ski/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Maciej Bliziński"
  homepage = "http://blizin.ski"
